### PR TITLE
fix #127 add reference to tmp-promise

### LINKED ISSUE #127: Task: Mention promise based API and link to project
Since people are asking for a promises based API #126, #74 we should include a reference to the project https://github.com/benjamingr/tmp-promise in the documentation.

### PR DESCRIPTION
**Pull request by silkentrance**

### CODE REVIEW

**Comment by silkentrance** [comment]
Since you provided no further input I assume that you are fine with the addition. Merging.

**Comment by raszi** [comment]
Sorry, I am on vacation. But I am fine with this change.

**Comment by raszi** [comment]
The reference links won't appear on GitHub. So we should explicitly link that.

**Comment by silkentrance** [comment]
Fixed. Added References section and made the references a bullet list, see

https://github.com/raszi/node-tmp/blob/gh-129/README.md

**Pull request merged**
