### PR TITLE
Add missing tests based on coverage report

### PR DESCRIPTION
**Pull request by silkentrance**
The coverage report from #107 shows that we are missing some tests.

This PR is about implementing additional tests so that we can increase our overall test coverage.

## TODO

- [x] invalid template option
- [ ] valid template option with pre existing file or dir
- [ ] TBD

### CODE REVIEW

**Comment by silkentrance** [comment]
@raszi never ever merge into existing PRs. this breaks the whole work flow and all the other PRs. You just increased the amount of work by a manifold. Yikes.

**Comment by silkentrance** [comment]
@raszi rebase is our friend here. rebase+merge gets the job done. and merge and then rebase will break everything.

**Comment by silkentrance** [comment]
@raszi I do not know what you did to master but all my rebases here are failing with arbitrary merge proposals. Did you push --force?

**Comment by silkentrance** [comment]
@raszi please use rebase wherever possible. I am a having a hard time with gh-121 and gh-155. while both have been resolved for now, merging these into master will take extra work...

**Comment by silkentrance** [comment]
wtf. is github bonkers or what? this cannot be merged, never.

**Comment by silkentrance** [comment]
@raszi for the record: I did not close this and i would have never merged into master.
This leaves the question: who did close and merge this?
image

**Comment by silkentrance** [comment]
@raszi seems as if this was closed (again) due to my latest push --force attempt to fix existing issues in the branch. Yikes. Github is becoming somewhat intransparent right now.

**Comment by raszi** [comment]
@silkentrance I strongly disagree with your view and so does [Linus Torvalds](https://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html).

We should not fake the history and since this is not a local branch of yours and somebody else could use it therefore you should **not** rebase the changes.

Merging the recent changes is a task what you did and therefore it should appear in the history. You should rather merge the changes, resolve the conflicts and push the merge commit to the remote branch. GitHub will only show the differences and of course since it won't have conflicts the branch will be mergeable.

**Comment by raszi** [comment]
Long story short, you should only rebase your local changes and never rebase anything what you've already pushed to a remote branch.

**Comment by raszi** [comment]
This PR is borked for some reason. GitHub shows no commits and no changes. :worried:

**Comment by raszi** [comment]
You did a couple of force pushes, which could mess up GitHub. I tried to recover the PR from my local git repository, see #165

**Pull request closed without merging**
