### PR TITLE
Graceful Cleanup should be the default

### PR DESCRIPTION
**Pull request by silkentrance**
make graceful cleanup the default and let user override that by calling setGracefulCleanup(false)

### CODE REVIEW

**Comment by silkentrance** [comment]
see also #194

**Comment by raszi** [comment]
Thank you for the work @silkentrance. I don't like this change, we should update the README file to set the expectations right, but definitely not alter the listeners.

I would like to get rid of this feature soon so changing the default behavior to remove is not a great way to get there.

**Comment by silkentrance** [comment]
@raszi Then I think that someone will have to work on the readme and add the missing information.

**Comment by silkentrance** [comment]
Not to mention that the information in the readme was already in there.

However, this requires a lot more effort - checking on whether a directory, and by that tree of that, is actually empty...

**Comment by silkentrance** [comment]
we might get around this by just calling upon rmdirSync and capturing the resulting exception, if the specific directory was not empty.

**Pull request closed without merging**
