### PR TITLE
[WIP] fix(unlink): unlink file even the file descriptor has been closed already

### LINKED ISSUE #31: npm test generates a bunch of uncleaned tmp files

### LINKED ISSUE #52: Cleanup fails
When I use the default parameters, and then call the cleanup callback when I'm done, I get the following error:

```shell
  1)  "after all" hook:
     Error: ENOTEMPTY, directory not empty 'C:\Users\Oliver\AppData\Local\Temp\tmp-17520mURkNFVU7XQ6'
      at Object.fs.rmdirSync (fs.js:624:18)
      at C:\Users\Oliver\prj\cli\test\prepare.js:39:3
      at Array.forEach (native)
      at Context.<anonymous> (C:\Users\Oliver\prj\cli\test\prepare.js:38:13)
```

I'm copying temporary files to that directory, so this wasn't surprising. I then set `unsafeCleanup` to `true` and now I get this result:

```
  1)  "after all" hook:
     Error: ENOENT, no such file or directory 'C:\Users\Oliver\AppData\Local\Temp\tmp-396iEctJyHwBoYu\corePath'
      at Object.fs.readdirSync (fs.js:666:18)
      at C:\Users\Oliver\prj\cli\test\prepare.js:39:3
      at Array.forEach (native)
      at Context.<anonymous> (C:\Users\Oliver\prj\cli\test\prepare.js:38:13)
```

The weirdest part is, the temporary directory is actually deleted just fine.

### PR DESCRIPTION
**Pull request by raszi**
Fixes #31 
Fixes #52

### CODE REVIEW

**Comment by raszi** [comment]
There are other issues in the test environment which need to be addressed.

**Comment by silkentrance** [comment]
@raszi with all of the current patches in place, including this one, test cases will no longer leave any temporary files a/o directories, at least this was the case when I last ran npm test on node-tmp.

**Comment by silkentrance** [comment]
@raszi Yes, you are correct in that other error codes might be returned.

Excerpt from the man page for close():

```
RETURN VALUE
       close() returns zero on success.  On error, -1 is returned, and errno is set appro‐
       priately.

ERRORS
       EBADF  fd isn't a valid open file descriptor.

       EINTR  The close() call was interrupted by a signal; see signal(7).

       EIO    An I/O error occurred.
```

And this why we would raise the exception again in case of either EINTR or EIO or anything other that is currently not on the menu.

However, and since close() is the final operation on that file, we should try to unlink the file in the finally block and hope that this will succeed, otherwise an exception would be raised there that will then be passed to the user.

**Comment by silkentrance** [comment]
Looking at both #58 and #52 it seems that the original try/catch around the fs.closeSync was correct, see https://github.com/raszi/node-tmp/commit/afe2af97fdd2c397e8b5c95575aacae05a0a0255#diff-4f99eaef47493ba13b06879592d2a1c4R199

It must, however, be extended to also test for ENOENT in case that the file was never created.

**Comment by silkentrance** [comment]
@raszi Please have a look at the mentioned issues and this pending PR.

**Comment by pabigot** [comment]
I haven't tested this change, but I have found that running the test suite on master leaves files such as:

    -rw------- 1 pab pab    9 Oct 10 05:24 /tmp/clike-4sx8F2-postfix
    -rw-r--r-- 1 pab pab    9 Oct 10 05:24 /tmp/complicated11606JjAUMfHSrvGboptions
    -rw-r----- 1 pab pab    9 Oct 10 05:24 /tmp/foo11606GlsM8RXoj4PLbar
    -rw------- 1 pab pab    9 Oct 10 05:24 /tmp/something11606sMsmYnHYbleK.tmp
    -rw------- 1 pab pab    9 Oct 10 05:24 /tmp/tmp-116067rh8MVJUQE7V.txt
    -rw------- 1 pab pab    9 Oct 10 05:24 /tmp/tmp-11606DpO5Ey7e2bSc.tmp
    
    /tmp/clike-esq0Fp-postfix:
    total 0
    
    /tmp/clike-p89ADH-postfix:
    total 0
    
    /tmp/complicated116065XbIidRimg8qoptions:
    total 0
    
    /tmp/foo11606rt26GugO2QiSbar:
    total 0
    
    /tmp/something116062DyohoPQzex1:
    total 0
    
    /tmp/something11606ezxoWJOdalis:
    total 0

Running the suite repeated can result in bogus suite failures because the tests are unable to obtain a unique file name after the maximum number of tries.

**Comment by silkentrance** [comment]
Most of this has already been included in master and it no longer shows any left over files when running tests, closing.

**Pull request closed without merging**
