### PR TITLE
Refactor to Typescript

### PR DESCRIPTION
**Pull request by silkentrance**
This is WIP

TODO

- [ ] documentation
- [ ] missing tests
- [ ] code clean up
- [ ] dist build and packaging (lerna?)
- [ ] integration test w/ javascript from dist
- [ ] integration test w/ typescript from dist

Thoughts

- [ ] split into multiple packages `@tmp` (core/legacy/sync/async/promise)
  - legacy is a drop in replacement for the old tmp package to make transition to the new API more easier

### CODE REVIEW

**Comment by silkentrance** [comment]
@jbjhjm I have added build jobs for this on both appveyor and travis-ci. The builds seem to work just fine, also on my windows abd linux machines. Perhaps you give this one a try and tell me your findings, if any.

**Comment by silkentrance** [comment]
node latest build on travis fails due to typedoc dependency restriction:

`typescript@"3.9.x || 4.0.x" from typedoc@0.19.2`

**Comment by jbjhjm** [comment]
Hi @silkentrance , tested on Win10 with Node 10.20 -- no errors found. Also, no more varying results when rerunning tests.

**Comment by silkentrance** [comment]
@raszi please have a look at this and tell me what you think.

**Comment by raszi** [comment]
Thank you @silkentrance for your hard work! I'll take a deeper look soon. Here are my first notes:

- [ ] We should provide a way to import only specific functions from the sync or async versions, something like:
  - `import { file } from 'tmp/dist/async';`
  - `import { dir ] from 'tmp/dist/sync';`
  - I don't really like the `dist/` part in the import statements, but I could not find a good way to avoid them.
- [ ] [eslint](https://eslint.org/) is recommended over tslint (example config [here](https://github.com/raszi/here-client/blob/master/package.json#L65-L87))
- [ ] [prettier](https://prettier.io/) should be also included (example config [here](https://github.com/raszi/here-client/blob/master/package.json#L115-L120))
- [ ] Avoid unnecessary classes and static functions, simply export functions (`PathUtils`, `RandomNameGenerator`, etc.)
- [ ] Functional `Array.map`, `Array.find` should be used instead of for loops

**Comment by silkentrance** [comment]
@raszi Thank you for the kind reply.

1) Yes, this is definitely something I would like to have, too. Especially breaking this up into sync/async and the default.
2) As for the import path, this can easily be fixed by having a build script that will prepare the distribution package from the dist folder and other artifacts, which will then be deployed to npmjs.com. This would also leave out the typescript sources, which are no longer needed.
3) Will switch to eslint.
4) I will have a look at prettier, haven't used that one before.
5) Coming from a Java background ... well, I will refactor these static methods into functions. As for the name generator being a class rather than a function: I will see what I can do about that, since I wanted to incorporate different naming strategies, one that uses the RND and one that uses for example UUID4.
6) Will refactor to map/find etc.

**Comment by raszi** [comment]
About the documentation I've recently used [TypeDoc](https://github.com/TypeStrong/TypeDoc), I believe it would be a more fitting choice to document the project.

**Comment by raszi** [comment]
> About the documentation I've recently used [TypeDoc](https://github.com/TypeStrong/TypeDoc), I believe it would be a more fitting choice to document the project.

Never mind, I've just realized that you switched to TypeDoc :)

**Comment by silkentrance** [comment]
@raszi  I have refactored the static methods to just module level functions. I also introduced three separate modules for the various interfaces, sync, async and promise, respectively.

As for Array.map and Array.find: some for loops cannot be changed as ArrayLike does not support the find/map methods, in addition, the parameters can be either Sets or Arrays, hence the ArrayLike.

I will have to see whether this can be refactored as well without having to copy the data from the set to an array and so on.

As for the unncessary classes, well, in the future I wanted to complement the random name generator by a uuid based name generator. Of course this could also be replaced by just factory functions.

There are still some things to be done, namely the hardcoded C: in the test utils, which should be replaced by whatever the %TEMP% environment variable points to.

**Comment by silkentrance** [comment]
Now with the mid terms out of the way I might finally manage to find some time to work on this a little further...

**Comment by silkentrance** [comment]
@raszi I managed to remove the dist part in the import by just moving all transpiled files to the top of the dist directory which is then the package root and from which new versions can be deployed to for example npm.

However, transpiling this means that we lose code insight with at least IntelliJ and WebStorm since they do not care about server side source maps and will display only the transpiled code on debug.

The typings work just fine with typescript code that imports from the transpiled files, though.

So my proposal would be to 

- move everything from src/ to the package root
- ditch the source maps
- transpile everything to the package root

and deploy from there.

This would give us an npm package that contains both the typescript sources and also the transpiled javascript code.
I will run some tests locally to see whether this integrated well into both a standard javascript workflow and a typescript based workflow.

**Pull request closed without merging**
