### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by silkentrance** [comment]
@dineshks1 Tmp does not have any native artifacts except for its node requirement.

Just out of curiosity, why would you need such a build job?

**Comment by silkentrance** [comment]
@dineshks1 I still require you to provide an answer as to why we would need the extra build target. Otherwise this PR will be closed without merging.

**Comment by dineshks1** [comment]
This is a part of Ubuntu distribution for ppc64le architecture. It will help us to simplify testing later when distributions are re-building and re-releasing.

**Comment by dineshks1** [comment]
Please review this merge. For more info tag @gerrith3.

**Comment by silkentrance** [comment]
@dineshks1 It was never merged. There are no system dependencies in tmp whatsoever. Why do you not just use the standard ci builds?

**Comment by silkentrance** [comment]
current and future travis-ci.org is taking hours to have a ci build, so, no, we will not  include this.

**Pull request closed without merging**
